//! Core types and interfaces for the VZGLYD kernel.
//!
//! This module defines the platform abstraction layer that allows the kernel
//! to run on any host (native wgpu, WebGL, WebGPU, etc.)

use serde::{Deserialize, Serialize};

/// Logging severity levels
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogLevel {
    Debug,
    Info,
    Warn,
    Error,
}

/// A request for data from the host
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataRequest {
    /// Key identifying the requested data (e.g., file path, URL, resource ID)
    pub key: String,
}

/// Platform-agnostic render commands
///
/// These commands are generated by the kernel and executed by the host
/// using its native graphics API (wgpu, WebGL, WebGPU, etc.)
#[derive(Debug, Clone)]
pub enum RenderCommand {
    /// Begin a new frame
    BeginFrame,

    /// End the current frame and present
    EndFrame,

    /// Bind a pipeline by kind
    BindPipeline {
        kind: PipelineKind,
    },

    /// Bind a texture to a specific slot
    BindTexture {
        slot: u32,
        /// Handle to the texture resource (host-specific interpretation)
        handle: TextureHandle,
    },

    /// Bind a sampler to a specific slot
    BindSampler {
        slot: u32,
        /// Handle to the sampler resource
        handle: SamplerHandle,
    },

    /// Bind a uniform buffer
    BindUniforms {
        /// Bind group index
        group: u32,
        /// Uniform data
        data: Vec<u8>,
    },

    /// Draw indexed geometry
    DrawIndexed {
        /// Number of indices to draw
        index_count: u32,
        /// Number of instances
        instance_count: u32,
        /// First index to read
        first_index: u32,
        /// Vertex offset
        vertex_offset: i32,
        /// First instance to draw
        first_instance: u32,
    },

    /// Draw non-indexed geometry
    Draw {
        /// Number of vertices to draw
        vertex_count: u32,
        /// Number of instances
        instance_count: u32,
        /// First vertex to draw
        first_vertex: u32,
        /// First instance to draw
        first_instance: u32,
    },

    /// Set the viewport
    SetViewport {
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        min_depth: f32,
        max_depth: f32,
    },

    /// Set the scissor rect
    SetScissor {
        x: u32,
        y: u32,
        width: u32,
        height: u32,
    },

    /// Clear the render target
    Clear {
        color: Option<[f32; 4]>,
        depth: Option<f32>,
    },

    /// Upload vertex data
    UploadVertexBuffer {
        /// Buffer handle (host-specific)
        handle: BufferHandle,
        /// Data to upload
        data: Vec<u8>,
    },

    /// Upload index data
    UploadIndexBuffer {
        /// Buffer handle (host-specific)
        handle: BufferHandle,
        /// Data to upload
        data: Vec<u8>,
    },

    /// Create a texture resource
    CreateTexture {
        /// Handle to assign to the new texture
        handle: TextureHandle,
        /// Width in pixels
        width: u32,
        /// Height in pixels
        height: u32,
        /// Format (e.g., RGBA8)
        format: TextureFormat,
        /// Initial data (optional)
        data: Option<Vec<u8>>,
    },

    /// Create a buffer resource
    CreateBuffer {
        /// Handle to assign to the new buffer
        handle: BufferHandle,
        /// Size in bytes
        size: u64,
        /// Usage flags
        usage: BufferUsage,
    },

    /// Destroy a texture resource
    DestroyTexture(TextureHandle),

    /// Destroy a buffer resource
    DestroyBuffer(BufferHandle),
}

/// Pipeline kind (opaque vs transparent)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PipelineKind {
    /// Opaque geometry with depth writing
    Opaque,
    /// Transparent geometry with depth testing only
    Transparent,
}

/// Texture handle (host interprets this)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TextureHandle(pub u32);

/// Sampler handle (host interprets this)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SamplerHandle(pub u32);

/// Buffer handle (host interprets this)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct BufferHandle(pub u32);

/// Texture format
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextureFormat {
    Rgba8Unorm,
    Rgba8UnormSrgb,
    Depth32Float,
}

/// Buffer usage flags
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BufferUsage {
    pub vertex: bool,
    pub index: bool,
    pub uniform: bool,
    pub storage: bool,
}

impl BufferUsage {
    pub const fn empty() -> Self {
        Self {
            vertex: false,
            index: false,
            uniform: false,
            storage: false,
        }
    }

    pub const fn vertex() -> Self {
        Self {
            vertex: true,
            index: false,
            uniform: false,
            storage: false,
        }
    }

    pub const fn index() -> Self {
        Self {
            vertex: false,
            index: true,
            uniform: false,
            storage: false,
        }
    }

    pub const fn uniform() -> Self {
        Self {
            vertex: false,
            index: false,
            uniform: true,
            storage: false,
        }
    }
}

/// Input to the engine update loop
#[derive(Debug, Clone, Default)]
pub struct EngineInput {
    /// Delta time in seconds
    pub dt: f32,
    /// Events since last update (resize, input, data responses)
    pub events: Vec<InputEvent>,
}

/// Events that can be sent to the engine
#[derive(Debug, Clone)]
pub enum InputEvent {
    /// Window was resized
    Resized {
        width: u32,
        height: u32,
    },
    /// Data request was fulfilled
    DataReady {
        key: String,
        data: Vec<u8>,
    },
    /// User input (for interactive slides)
    UserInput {
        kind: InputKind,
    },
}

/// User input kind
#[derive(Debug, Clone)]
pub enum InputKind {
    /// Mouse/touch position
    Position { x: f32, y: f32 },
    /// Mouse button or touch start/end
    Button { pressed: bool },
    /// Keyboard input
    Key { code: String, pressed: bool },
}

/// Output from the engine update loop
#[derive(Debug, Clone, Default)]
pub struct EngineOutput {
    /// Render commands to execute
    pub commands: Vec<RenderCommand>,
    /// Current engine state
    pub state: EngineState,
    /// Data requests for the host to fulfill
    pub requests: Vec<DataRequest>,
}

/// Current engine state
#[derive(Debug, Clone, Default)]
pub struct EngineState {
    /// Current slide index in the schedule
    pub schedule_index: usize,
    /// Total slides in schedule
    pub total_slides: usize,
    /// Elapsed time in current slide
    pub elapsed_secs: f32,
    /// Current FPS
    pub fps: f32,
    /// Whether a transition is active
    pub is_transitioning: bool,
    /// Whether the engine is ready to render
    pub is_ready: bool,
}

/// The Host trait defines the platform abstraction layer.
///
/// The kernel calls into the Host to:
/// - Request external data (files, network, etc.)
/// - Submit render commands for execution
/// - Log messages
/// - Get timing information
pub trait Host {
    /// Request external data asynchronously
    ///
    /// The host should fulfill this request and send back a `DataReady` event
    /// via the next `EngineInput`. Returns `None` if data is not available.
    fn request_data(&mut self, key: &str) -> Option<Vec<u8>>;

    /// Submit render commands for immediate execution
    fn submit_render_commands(&mut self, cmds: &[RenderCommand]);

    /// Log a message at the specified level
    fn log(&mut self, level: LogLevel, msg: &str);

    /// Get the current time in seconds (for timing calculations)
    fn now(&self) -> f32;
}
